# Generated by Django 3.0.6 on 2020-06-01 03:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('embed', models.URLField(max_length=255)),
                ('title', models.TextField()),
                ('slug', models.SlugField(default='', editable=False, max_length=255)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.CharField(blank=True, max_length=50, null=True)),
                ('screenshot', models.URLField(default='', max_length=255)),
                ('trailer', models.URLField(blank=True, default='', max_length=255, null=True)),
                ('actor', models.TextField(blank=True, default='', null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', null=True), size=None)),
                ('flipbook', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), blank=True, null=True, size=None)),
                ('views', models.CharField(blank=True, max_length=255, null=True)),
                ('media_type', models.CharField(max_length=50)),
                ('partner', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'videos',
                'ordering': ('title',),
            },
        ),
    ]
